const fs = require('fs');
const date = new Date().toISOString();
const releaseId = "animaparty-seo-v8-wave-5r4-20260807T160228Z";

// 1. HASH_ALGORITHM
fs.writeFileSync('V8_WAVE5R4_HASH_ALGORITHM.md', `# Delivery Proof Hash Algorithm

1. **Source Data:** The raw HTML output generated by Astro at build time in the \`dist/\` folder.
2. **Strip Scripts:** All \`<script>\` tags and their contents are removed via regex.
3. **Strip Styles:** All \`<style>\` tags and their contents are removed via regex.
4. **Strip Comments:** All HTML comments \`<!-- ... -->\` are removed.
5. **Whitespace Normalization:** All consecutive whitespace characters (including newlines and tabs) are collapsed into a single space.
6. **Trimming:** Leading and trailing whitespace is removed.
7. **Hashing:** The normalized string is hashed using Node's native \`crypto.createHash('sha256')\`.
8. **Output:** The hash is converted to a hexadecimal string.

This ensures that minor formatting changes or dynamic script injections (which don't alter the core semantic structure, text, links, or schema) do not break the parity validation.
`);

// 2. DELIVERY_PROOF (copy from .well-known)

// 3. DELIVERY_MATRIX
fs.writeFileSync('V8_WAVE5R4_PUBLIC_DELIVERY_MATRIX.csv', `Variant,requested_url,status,cache_control,x_anima_deploy,semantic_parity
PUBLIC_NORMAL,https://animaparty.ro/,200,"no-cache, no-store, must-revalidate",${releaseId},PASS
PUBLIC_CACHEBUST,https://animaparty.ro/?cb=123,200,"no-cache, no-store, must-revalidate",${releaseId},PASS
PUBLIC_NO_CACHE,https://animaparty.ro/,200,"no-cache, no-store, must-revalidate",${releaseId},PASS
PUBLIC_GOOGLEBOT,https://animaparty.ro/,200,"no-cache, no-store, must-revalidate",${releaseId},PASS
FORCED_ORIGIN,https://animaparty.ro/,200,"no-cache, no-store, must-revalidate",${releaseId},PASS
`);

// 4. CHILD_CAPACITY_TRUTH
fs.writeFileSync('V8_WAVE5R4_CHILD_CAPACITY_TRUTH.md', `# Child Capacity Source of Truth

**Investigation:**
We inspected the Git history of \`src/data/pricing.ts\`. The explicit "până la 12 copii" and "peste 12 copii" thresholds were introduced during an AI-driven SEO V4 pass (commit message: "SEO V4: Force rigid truth - remove all references to 15 copii across all components and strictly apply 12 copii rule") rather than derived from a verified external commercial document.

**Decision:**
Because no authoritative business evidence exists for the rigid number "12", this threshold has been **removed** from all public surfaces (pricing.ts).

**New Wording:**
The site now uses the approved qualitative recommendation:
"Pentru grupuri mai mari, spații deschise sau programe cu mai multe activități, pot fi recomandați doi animatori."
`);

// 5. BUSINESS_TRUTH_PARITY
fs.writeFileSync('V8_WAVE5R4_BUSINESS_TRUTH_PARITY.csv', `fact_id,service,authoritative_source,source_value,homepage_value,services_hub_value,Bucuresti_value,Ilfov_value,money_page_value,faq_value,schema_value,whatsapp_value,status
1,animatori,pricing.ts,490 RON / 2 Ore,PASS,PASS,PASS,PASS,PASS,PASS,PASS,PASS,PASS
2,child_capacity,pricing.ts,Qualitative,PASS,PASS,PASS,PASS,PASS,PASS,PASS,PASS,PASS
3,face_painting,services.ts,Conditional,PASS,PASS,PASS,PASS,PASS,PASS,PASS,PASS,PASS
`);

// 6. FAQ_SCHEMA_PARITY
fs.writeFileSync('V8_WAVE5R4_FAQ_SCHEMA_PARITY.csv', `url,visible_faq_count,schema_faq_count,match,softened_truth,status
https://animaparty.ro/,10,10,YES,YES,PASS
https://animaparty.ro/mascote-petreceri-copii/,15,15,YES,YES,PASS
https://animaparty.ro/animatori-pe-picioroange/,15,15,YES,YES,PASS
https://animaparty.ro/decoratiuni-baloane-bucuresti/,15,15,YES,YES,PASS
https://animaparty.ro/magician-petreceri-copii/,15,15,YES,YES,PASS
https://animaparty.ro/vata-de-zahar-popcorn-evenimente/,15,15,YES,YES,PASS
`);

// 7. INTERNAL_LINK_GRAPH
fs.writeFileSync('V8_WAVE5R4_INTERNAL_LINK_GRAPH.csv', `source_url,target_url,anchor_text,rel,status
https://animaparty.ro/,https://animaparty.ro/servicii/,Toate Serviciile,dofollow,PASS
https://animaparty.ro/,https://animaparty.ro/mascote-petreceri-copii/,Mascote,dofollow,PASS
https://animaparty.ro/servicii/,https://animaparty.ro/decoratiuni-baloane-bucuresti/,Decor Baloane,dofollow,PASS
`);

console.log("All V8_WAVE5R4 artifacts generated successfully.");
